After dispatch hook
mdeloof/statig pull request #23
Opened 2024-04-18 13:58 UTC by dragonnn

Although on_dispatch and on_transition hook are intend to be used for loging in some cases it can be useful to abuse them to have a global even handler that stores some filtered events in self. For that case it sometimes makes sense to be able to store something in self after a state handler is called to for example use it for storing previous values that can be used when a new value comes in to compare too.

2025-01-01 23:39 UTC, mdeloof commented
I'm open to adding an `after_dispatch` hook, but we should then probably rename `on_dispatch` to `before_dispatch`, and `on_transition` to `after_transition`. For completeness sake we should probably also add `before_transition`.

(My apologies for not responding to this sooner. I'll try to be more responsive going forward :) )

2025-01-02 06:11 UTC, dragonnn commented
Thanks for looking into it! I do agree renaming all of those and adding before before_transition. Do you want all of that in this PR?

2025-01-02 18:40 UTC, mdeloof commented
Yes, if you want to, you can go ahead and make the changes on this PR. But if you're not able to do it at the moment, just let me know and I'll see what I can do.

2025-01-05 10:11 UTC, dragonnn commented
Sorry for the delay, should be done. I don't think I missed anything. I renamed the consts for hooks to uppercase in IntoStateMachine too as suggested by clippy.

2025-01-05 20:29 UTC, christianheussy commented
Isn't this a breaking change? I would think the manifest version should be revised to `0.4.0`. Alternatively, maybe the macro could still support the previous names and emit a warning that they are deprecated?

2025-01-05 21:12 UTC, dragonnn commented
Definitely a breaking change, if you would like to have the version bump in this PR too I am will add that right away, didn't do it because I am not sure how you would like to manage that.

2025-01-07 21:22 UTC, mdeloof requested changes
I think you forgot to call `M::BEFORE_TRANSITION()` in the `transition()` function? :) Other than that everything looks good, just a couple of comments with the wrong name.

Regarding the version bump, you can change it to 0.4.0 for both the `statig` and `statig_macro` crate.

2025-01-07 21:22 UTC, mdeloof commented on examples/macro/async_blinky/src/main.rs
> +    // Set the `before_dispatch` callback.
```suggestion
    // Set the `after_dispatch` callback.
```

2025-01-07 21:22 UTC, mdeloof commented on examples/macro/async_blinky/src/main.rs
> +    // Set the `before_dispatch` callback.
```suggestion
    // Set the `before_transition` callback.
```

2025-01-07 21:22 UTC, mdeloof commented on examples/macro/async_blinky/src/main.rs
> +        println!("after transitioned from `{source:?}` to `{target:?}`");
```suggestion
        println!("before transitioned from `{source:?}` to `{target:?}`");
```

2025-01-07 21:55 UTC, christianheussy commented on statig/src/lib.rs
> +//!     after_transition = "Self::after_transition",
Looks like `before_transition` is missing here.

2025-01-07 21:55 UTC, christianheussy commented on statig/src/lib.rs
> +//! - `before_dispatch` is called before an event is dispatched to a specific state or superstate.
Looks like `before_transition` is missing here.

2025-01-07 21:55 UTC, christianheussy commented on statig/src/lib.rs
> +//!     fn before_dispatch(&mut self, state: StateOrSuperstate<Blinky>, event: &Event) {
Looks like `before_transition` is missing here.

2025-01-08 09:17 UTC, dragonnn commented
Thanks! I hope I didn't missing anything, should be fine now

2025-01-08 17:54 UTC, mdeloof requested changes
Thanks! Almost there I think, just a small error in the docs left. You will also have to bump the version of the `statig_macro` dependency in [`/statig/Cargo.toml`](https://github.com/mdeloof/statig/blob/main/statig/Cargo.toml).

```diff
[dependencies]
-statig_macro = { path = "../macro", version = "0.3.0", optional = true }
+statig_macro = { path = "../macro", version = "0.4.0", optional = true }
```

2025-01-08 17:54 UTC, mdeloof commented on README.md
> +        println!("after dispatched `{:?}` to `{:?}`", event, state);
There are two copies here of `before_dispatch` as well as `after_transition`, and no `after_dispatch` and `before_transition`.

2025-01-08 18:17 UTC, dragonnn commented
Oh, my bad! Sorry, I should catch that. Should be fine now :)

2025-01-08 18:43 UTC, merged

2025-01-08 18:44 UTC, mdeloof commented
No problem ;) Thanks again for your work!